apiVersion: apps/v1
kind: Deployment
metadata:
  name: konfi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konfi-ui
  template:
    metadata:
      labels:
        app: konfi-ui
    spec:
      containers:
        - name: konfi-ui
          image: konfi-ui:latest
          ports:
            - containerPort: 4000
              hostPort: 4000
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: konfi-ui-config

          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 400m
              memory: 500Mi