apiVersion: apps/v1
kind: Deployment
metadata:
  name: konfi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konfi-back
  template:
    metadata:
      labels:
        app: konfi-back
    spec:
      containers:
        - name: konfi-back
          image: konfi-back:latest
          ports:
            - containerPort: 8080
              hostPort: 8080
              name: http
            - containerPort: 8080
              hostPort: 8000
              name: ws
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 800m
              memory: 2000Mi