apiVersion: apps/v1
kind: Deployment
metadata:
  name: konfi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konfi-back
  template:
    metadata:
      labels:
        app: konfi-back
    spec:
      containers:
        - name: konfi-back
          image: konfi-back:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: url
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: password
            - name: DATABASE_PLATFORM
              value: "org.hibernate.dialect.MySQLDialect"
            - name: DATABASE_DRIVER_CLASSNAME
              value: "com.mysql.jdbc.Driver"
          ports:
            - containerPort: 8080
              hostPort: 8080
              name: http
            - containerPort: 8080
              hostPort: 8000
              name: ws
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
              scheme: HTTP
            initialDelaySeconds: 60

          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 800m
              memory: 2000Mi