apiVersion: v1
kind: Service
metadata:
  name: konfi
  labels:
    service.kubernetes.io/service-name: "konfi-backend"
    service.kubernetes.io/service-proxy-name: "konfi-back"
spec:
  selector:
    app: konfi
  internalTrafficPolicy: Cluster
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: tcp-8080
    - targetPort: 8000
      port: 8000
      appProtocol: kubernetes.io/ws
      name: tcp-8000


