apiVersion: apps/v1
kind: Deployment
metadata:
  name: konfi
spec:
  selector:
    matchLabels:
      app: konfi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: konfi
    spec:
      containers:
        - image: mysql:9
          name: konfi-mysql
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: konfi-pvc