apiVersion: apps/v1
kind: Deployment
metadata:
  name: konfi-mysql
spec:
  selector:
    matchLabels:
      app: konfi-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: konfi-mysql
    spec:
      containers:
        - image: mysql:9
          name: konfi-mysql
          env:
            # Use secret in real usage
              valueFrom:
                secretKeyRef:
                  name: mysql-root-password
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: konfi-pvc