apiVersion: apps/v1
kind: Deployment
metadata:
  name: konfi-mysql
spec:
  selector:
    matchLabels:
      app: konfi-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: konfi-mysql
    spec:
      containers:
        - image: mysql:9
          name: konfi-mysql
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-config
                key: password
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: database-config
                key: name
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: database-config
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-config
                key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: konfi-pvc