apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: konfi
  name: router
  annotations:
    cert-manager.io/issuer: dev-letsencrypt-nginx
    cert-manager.io/certificate-name: dev-letsencrypt-nginx
    cert-manager.io/common-name: konfi-dev.denic0la.ch
    nginx.org/websocket-services: "konfi-back"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/server-snippets: |
      location /native {
       proxy_set_header Upgrade $http_upgrade;
       proxy_http_version 1.1;
       proxy_set_header X-Forwarded-Host $http_host;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Forwarded-For $remote_addr;
       proxy_set_header Host $host;
       proxy_set_header Connection "upgrade";
       proxy_cache_bypass $http_upgrade;
       }
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - konfi-dev.denic0la.ch
      secretName: dev-letsencrypt-nginx
  rules:
    - host: konfi-dev.denic0la.ch
      http:
        paths:
          - path: "/native"
            pathType: Prefix
            backend:
              service:
                name: konfi-back
                port:
                  number: 80
          - path: "/sockJs"
            pathType: Prefix
            backend:
              service:
                name: konfi-back
                port:
                  number: 80
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: konfi-ui
                port:
                  number: 80

