apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-nginx
spec:
  acme:
    email: nicola@fioretti.info
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-nginx-private-key-dev
    solvers:
      # Use the HTTP-01 challenge provider
      - http01:
          ingress:
            class: nginx