apiVersion: v1
kind: Service
metadata:
  name: konfi-nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      name: tcp-443


