apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: konfi
  name: router
  annotations:
    cert-manager.io/issuer: letsencrypt-nginx
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - stage.host
      secretName: letsencrypt-nginx-private-key-dev
  rules:
    - host: stage.host
      http:
        paths:
          - path: "/native"
            pathType: Prefix
            backend:
              service:
                name: konfi-back
                port:
                  number: 80
          - path: "/sockJs"
            pathType: Prefix
            backend:
              service:
                name: konfi-back
                port:
                  number: 80
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: konfi-ui
                port:
                  number: 80

